name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  fmt:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check formatting
        run: deno fmt --check

  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check theme is updated
        run: deno task check
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "theme"
